In [4]:
import numpy as np
from sympy import Matrix
import matplotlib.pyplot as plt
import seaborn as sns


In [2]:
# Step 1: Create Personal Matrix A based on ID formula
d1 = 0
d2 = 1

A = np.array([
    [d1 + 2, d2 + 1],
    [2 * d1, d2 + 2]
], )

# STEP 2: Analyze Matrix A
# 1. Size of a matrix
size_A = A.shape  # Returns dimensions (rows, columns)

print("Matrix A:\n", A)
print("Shape of A:", size_A)

# 2. Determinant of a matrix
det_A = np.linalg.det(A)  # Returns the determinant of the matrix
print("Determinant of A:", det_A)

# 3. Rank of a matrix
rank_A = np.linalg.matrix_rank(A)  # Returns the rank of the matrix
print("Rank of A:", rank_A)

# 4. Eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)  # Compute eigenvalues and eigenvectors
print("Eigenvalues of A:", eigenvalues)
print("Eigenvectors of A:\n", eigenvectors)

# 5. Inverse of a matrix
if np.linalg.det(A) != 0:  # Check if matrix is invertible
    inv_A = np.linalg.inv(A)  # Compute the inverse of A
else:
    inv_A = "Matrix is singular, cannot compute inverse"  # No inverse if determinant is 0

print("Inverse of A:\n", inv_A)

# Step 3: Value Change Experiment (Matrix B)
# Changing element at position (0, 0) by adding +1
B = A.copy()
B[0, 0] = B[0, 0] + 1  # Element A[0,0] updated from 2 to 3
print("Matrix B:\n", B)

# 1. Size of B matrix
size_B = B.shape  # Returns dimensions (rows, columns)
print("Shape of B:", size_B)

# 2. Determinant of B matrix
det_B = np.linalg.det(B)  # Returns the determinant of the matrix
print("Determinant of B:", det_B)

# 3. Rank of B matrix
rank_B = np.linalg.matrix_rank(B)  # Returns the rank of the matrix
print("Rank of B:", rank_B)

# 4. Eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(B)  # Compute eigenvalues and eigenvectors
print("Eigenvalues of B:", eigenvalues)
print("Eigenvectors of B:\n", eigenvectors)

# 5. Inverse of B matrix
if np.linalg.det(B) != 0:  # Check if matrix is invertible
    inv_B = np.linalg.inv(B)  # Compute the inverse of A
else:
    inv_B = "Matrix is singular, cannot compute inverse"  # No inverse if determinant is 0

print("Inverse of B:\n", inv_B)





Matrix A:
 [[2 2]
 [0 3]]
Shape of A: (2, 2)
Determinant of A: 6.0
Rank of A: 2
Eigenvalues of A: [2. 3.]
Eigenvectors of A:
 [[1.         0.89442719]
 [0.         0.4472136 ]]
Inverse of A:
 [[ 0.5        -0.33333333]
 [ 0.          0.33333333]]
Matrix B:
 [[3 2]
 [0 3]]
Shape of B: (2, 2)
Determinant of B: 9.000000000000002
Rank of B: 2
Eigenvalues of B: [3. 3.]
Eigenvectors of B:
 [[ 1.00000000e+00 -1.00000000e+00]
 [ 0.00000000e+00  3.33066907e-16]]
Inverse of B:
 [[ 0.33333333 -0.22222222]
 [ 0.          0.33333333]]


In [3]:
# 5. Comparison & Explanation

# 1. How did the determinant change and why?
# The determinant changed from 6 to 9 because the value of one matrix element
# was increased (A[0,0] from 2 to 3). Changing any element of a matrix can
# change its determinant, which represents the scaling factor of the matrix.

# 2. Did the rank change? Explain.
# No, the rank did not change. Both matrices have rank 2 because their
# determinants are non-zero, which means both matrices are full-rank and
# their rows and columns remain linearly independent.

# 3. How did the eigenvalues respond to the value change?
# The eigenvalues changed after modifying the matrix. Since eigenvalues depend
# on the entries of the matrix, changing one element changes the characteristic
# equation, resulting in different eigenvalues.

# 4. Is B easier or harder to invert than A? Why?
# B is just as easy to invert as A because both matrices have non-zero
# determinants. Since det(B) = 9 is larger than det(A) = 6, B is slightly
# farther from being singular, but both matrices are invertible using the
# same method.